# Generated by Django 4.1.2 on 2022-10-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='first_image',
        ),
        migrations.AddField(
            model_name='product',
            name='second_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
