# Generated by Django 4.1.2 on 2022-11-14 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_payment_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='price',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
