# Generated by Django 4.1.2 on 2022-11-14 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_payment_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='price',
            field=models.FloatField(),
        ),
    ]
