# Generated by Django 4.1.2 on 2022-11-14 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_payment_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
