# Generated by Django 4.1.2 on 2022-11-15 07:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0005_alter_payment_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='Stripe_Payment',
        ),
    ]
