# Generated by Django 4.1.2 on 2022-11-19 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_paypal_payment_remove_commodity_price_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paypal_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.paypal_payment'),
        ),
    ]
