# Generated by Django 4.1.2 on 2022-11-19 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_physical_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='physical_payment',
            old_name='paypal_charge_id',
            new_name='physical_charge_id',
        ),
    ]
