# Generated by Django 4.1.2 on 2022-11-19 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_rename_paypal_charge_id_physical_payment_physical_charge_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='physical_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.physical_payment'),
        ),
    ]
