# Generated by Django 4.1.2 on 2022-11-23 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_remove_order_shipping_address_shippingaddress_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physical_payment',
            name='user',
        ),
        migrations.AddField(
            model_name='physical_payment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.customer'),
        ),
    ]
