# Generated by Django 4.1.2 on 2022-11-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_remove_physical_payment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
