# Generated by Django 4.1.2 on 2022-11-30 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_remove_order_physical_payment_physical_payment_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physical_payment',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='physical_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.physical_payment'),
        ),
    ]
