# Generated by Django 4.1.2 on 2022-11-30 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_remove_physical_payment_order_order_physical_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='physical_payment',
        ),
        migrations.AddField(
            model_name='physical_payment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.order'),
        ),
    ]
